### ISSUE TITLE
v7 configuration error

### ISSUE THREAD

**Issue by ollym** [workos/workos-ruby#462]
We used to have this

```ruby
# app/initializers/workos.rb
WorkOS.configure do |config|
  config.api_key = Rails.application.credentials.workos_key
  config.client_id = Rails.application.credentials.workos_client_id
end
```

After upgrading to v7 we started getting this error:

`undefined method 'configure' for module WorkOS (NoMethodError)`

Had to put `require 'workos/configuration'` at the top of the initializer which seems wrong.

**Comment by gjtorikian** [comment]
Good call, this will be fixed in 7.1
